name: Auto Update Horoscope JSON

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install requests beautifulsoup4 googletrans==4.0.0-rc1  # Install required libraries

      - name: Fetch New Horoscope Data
        run: python update_horoscope.py  # Runs our Python script to fetch and update data

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add daily_horoscope.json
          git commit -m "Auto-update daily_horoscope.json"
          git push
